# Generated by Django 5.0.1 on 2024-06-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_brand_product_discount_product_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
