# Generated by Django 5.0.1 on 2024-06-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_logo',
            field=models.ImageField(blank=True, null=True, upload_to='category_logos/'),
        ),
    ]
