# Generated by Django 5.0.1 on 2024-06-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_category_cat_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_title', models.CharField(help_text='Small title above the main title', max_length=255)),
                ('large_title', models.TextField(help_text='Main large title')),
                ('image', models.ImageField(help_text='Image for the banner', upload_to='banners/')),
                ('button_link', models.URLField(help_text='URL that the button links to')),
            ],
        ),
    ]
