# Generated by Django 5.0.1 on 2024-06-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_banner_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the deal', max_length=255)),
                ('subtitle', models.CharField(blank=True, help_text='Subtitle of the deal', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the deal', null=True)),
                ('image', models.ImageField(help_text='Background image for the deal', upload_to='deals/')),
                ('new_price', models.DecimalField(decimal_places=2, help_text='New price of the deal', max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, help_text='Old price of the deal', max_digits=10, null=True)),
                ('countdown_end', models.DateTimeField(help_text='End date and time for the countdown')),
                ('product_link', models.URLField(help_text='Link to the product')),
                ('shop_link', models.URLField(help_text='Link to the shop page')),
            ],
        ),
    ]
