# Generated by Django 5.0.1 on 2024-06-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_deal'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the brand', max_length=255)),
                ('image', models.ImageField(help_text='Logo of the brand', upload_to='brands/')),
            ],
        ),
    ]
