# Generated by Django 5.0.1 on 2024-06-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_forget_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='forget_otp',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
