# Generated by Django 5.0.6 on 2024-06-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_shippingaddress_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='number',
            field=models.PositiveIntegerField(blank=True, max_length=15, null=True),
        ),
    ]
