# Generated by Django 5.0.6 on 2024-06-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_billingaddress_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
