# Generated by Django 5.0.6 on 2024-06-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_billingaddress_user_alter_shippingaddress_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
